var HARDWARE = {
 "kategorien": [
  "mini-pc",
  "gpu",
  "server",
  "nas"
 ],
 "produkte": [
  {
   "name": "Beelink SER8 (8745HS)",
   "hersteller": "Beelink",
   "kategorie": "mini-pc",
   "spezifikation": "AMD Ryzen 7 8745HS, 8C/16T, bis 4.9GHz, 35W TDP | max 64GB DDR5 (2x SO-DIMM) | 2x M.2 2280 PCIe 4.0 | 1x 2.5GbE, Wi-Fi 6, 2x USB4 40Gbps",
   "vram_gb": null,
   "ram_gb": 32,
   "idle_watt": 15,
   "tdp_watt": null,
   "preis_eur": 899,
   "benchmark": "",
   "einschaetzung": "Starker 8-Kern fuer Proxmox/VMs, aber Idle-Verbrauch teils hoch gemessen (8745HS-Boost-Problem).",
   "link": "https://geizhals.de/beelink-ser8-a3920822.html"
  },
  {
   "name": "Beelink SER7 (7840HS)",
   "hersteller": "Beelink",
   "kategorie": "mini-pc",
   "spezifikation": "AMD Ryzen 7 7840HS, 8C/16T, bis 5.1GHz | max 64GB DDR5 | 2x M.2 | 2x 2.5GbE, USB4, HDMI 2.1",
   "vram_gb": null,
   "ram_gb": 32,
   "idle_watt": 9,
   "tdp_watt": null,
   "preis_eur": 679,
   "benchmark": "",
   "einschaetzung": "Bewaehrter Klassiker mit 2x 2.5GbE, sehr gutes Preis/Leistung fuer Homelab.",
   "link": "https://www.idealo.de/preisvergleich/Liste/120159649/beelink-ser-7.html"
  },
  {
   "name": "Beelink Mini S12 Pro (N100)",
   "hersteller": "Beelink",
   "kategorie": "mini-pc",
   "spezifikation": "Intel N100, 4C/4T, bis 3.4GHz, 6-25W TDP | max 16GB DDR4 (1x SO-DIMM) | 1x M.2 2280 + 2.5\" SATA | 1x 2.5GbE, Wi-Fi 6, Dual HDMI",
   "vram_gb": null,
   "ram_gb": 16,
   "idle_watt": 7,
   "tdp_watt": null,
   "preis_eur": 200,
   "benchmark": "",
   "einschaetzung": "Guenstigster, sehr sparsamer Einstieg fuer Router/Firewall/kleine 24/7-Dienste.",
   "link": "https://www.idealo.de/preisvergleich/OffersOfProduct/203489921_-mini-s12-pro-n100-16gb-500gb-beelink.html"
  },
  {
   "name": "Minisforum UM780 XTX (7840HS)",
   "hersteller": "Minisforum",
   "kategorie": "mini-pc",
   "spezifikation": "AMD Ryzen 7 7840HS, 8C/16T, bis 5.1GHz, bis 70W | max 96GB DDR5 (2x SO-DIMM) | 2x M.2 2280 PCIe 4.0 | 2x 2.5GbE (2x RJ45), 2x USB4, OCuLink, HDMI 2.1",
   "vram_gb": null,
   "ram_gb": 32,
   "idle_watt": 12,
   "tdp_watt": null,
   "preis_eur": 550,
   "benchmark": "",
   "einschaetzung": "Sehr gut ausgestattet (2x 2.5GbE + OCuLink), ideal fuer Proxmox+NAS.",
   "link": "https://www.idealo.de/preisvergleich/Liste/120361982/minisforum-elitemini-um780-xtx.html"
  },
  {
   "name": "Minisforum UM890 Pro (8945HS)",
   "hersteller": "Minisforum",
   "kategorie": "mini-pc",
   "spezifikation": "AMD Ryzen 9 8945HS, 8C/16T, bis 5.2GHz | max 96GB DDR5 | 2x M.2 2280 PCIe 4.0 | 2x 2.5GbE (2x RJ45), 2x USB4, OCuLink",
   "vram_gb": null,
   "ram_gb": 0,
   "idle_watt": 8,
   "tdp_watt": null,
   "preis_eur": 479,
   "benchmark": "",
   "einschaetzung": "Sehr effizienter 8-Kern mit 2x 2.5GbE + OCuLink, top Wahl fuer Homelab-Virtualisierung.",
   "link": "https://geizhals.de/minisforum-um890-pro-a3286602.html"
  },
  {
   "name": "ASUS NUC 14 Pro",
   "hersteller": "ASUS (Intel NUC)",
   "kategorie": "mini-pc",
   "spezifikation": "Intel Core Ultra 5 125H / Ultra 7 155H / Ultra 9 185H (bis 14C/18T) | max 96GB DDR5 (2x SO-DIMM) | 2x M.2 (2280 + 2242) | 1x 2.5GbE (i226), 2x Thunderbolt 4, vPro",
   "vram_gb": null,
   "ram_gb": 0,
   "idle_watt": 8,
   "tdp_watt": null,
   "preis_eur": 260,
   "benchmark": "",
   "einschaetzung": "Solider Marken-Standard mit vPro/AMT und sehr sparsam, aber nur 1x 2.5GbE.",
   "link": "https://geizhals.de/asus-nuc-14-pro-kit-barebone-v158051.html"
  },
  {
   "name": "GMKtec K8 Plus (8845HS)",
   "hersteller": "GMKtec",
   "kategorie": "mini-pc",
   "spezifikation": "AMD Ryzen 7 8845HS, 8C/16T, bis 5.1GHz, 65W | max 96GB DDR5 5600 (GMKtec listet 48GB) | 2x M.2 2280 PCIe 4.0 (je bis 4TB) | 2x 2.5GbE, 2x USB4 40Gbps, OCuLink, HDMI 2.1 + DP 2.1",
   "vram_gb": null,
   "ram_gb": 32,
   "idle_watt": 14,
   "tdp_watt": null,
   "preis_eur": 520,
   "benchmark": "",
   "einschaetzung": "Preiswerter 8845HS mit 2x 2.5GbE + OCuLink, Idle etwas hoeher als UM890 Pro.",
   "link": "https://de.gmktec.com/en/products/gmktec-nucbox-k8-plus-amd-ryzen%E2%84%A2-7-8845hs-mini-pc"
  },
  {
   "name": "Lenovo ThinkCentre M90q Gen 5",
   "hersteller": "Lenovo",
   "kategorie": "mini-pc",
   "spezifikation": "Intel Core i5-14500T / i7 / i9-14900 (35/65W T) | max 64GB DDR5 (2x SO-DIMM) | 2x M.2 + optional 2.5\" SATA | 1x 2.5GbE (Intel i226), optional 2nd, vPro/AMT",
   "vram_gb": null,
   "ram_gb": 16,
   "idle_watt": 11,
   "tdp_watt": null,
   "preis_eur": 900,
   "benchmark": "",
   "einschaetzung": "Business-Klasse mit vPro/AMT und Top-Verarbeitung, aber deutlich teurer.",
   "link": "https://geizhals.de/lenovo-thinkcentre-m90q-gen-5-12th002jge-a3355645.html"
  },
  {
   "name": "Lenovo ThinkCentre M75q Gen 5",
   "hersteller": "Lenovo",
   "kategorie": "mini-pc",
   "spezifikation": "AMD Ryzen 5 PRO 8500GE (6C/12T) / Ryzen 7 PRO 8700GE | max 64GB DDR5 (2x SO-DIMM) | 2x M.2 (2280 + 2230/2242) | 1x 2.5GbE, optional 2nd, Pro-Features",
   "vram_gb": null,
   "ram_gb": 16,
   "idle_watt": 10,
   "tdp_watt": null,
   "preis_eur": 580,
   "benchmark": "",
   "einschaetzung": "AMD-Alternative mit Pro-Features und potenziell sehr niedrigem Idle.",
   "link": "https://geizhals.de/lenovo-thinkcentre-m75q-gen-5-tiny-v200680.html"
  },
  {
   "name": "GeForce RTX 3060 12GB",
   "hersteller": "NVIDIA (Partner: MSI, Gigabyte, ASUS u.a.)",
   "kategorie": "gpu",
   "spezifikation": "12GB GDDR6, 192-Bit-Bus, 360 GB/s",
   "vram_gb": 12,
   "ram_gb": null,
   "idle_watt": null,
   "tdp_watt": 170,
   "preis_eur": 307,
   "benchmark": "~30-35 tok/s @7B-Q4 (geschätzt, speicherbandbreiten-limitiert)",
   "einschaetzung": "Günstigster solider Einstieg für 7B-Q4 (12GB reichen auch für 13B-Q4), aber Neupreis 2026 stark überzogen.",
   "link": "https://geizhals.de/msi-geforce-rtx-3060-v66881.html"
  },
  {
   "name": "GeForce RTX 4060 Ti 16GB",
   "hersteller": "NVIDIA (Partner: MSI, ASUS u.a.)",
   "kategorie": "gpu",
   "spezifikation": "16GB GDDR6, 128-Bit-Bus, 288 GB/s",
   "vram_gb": 16,
   "ram_gb": null,
   "idle_watt": null,
   "tdp_watt": 165,
   "preis_eur": 625,
   "benchmark": "~28-32 tok/s @7B-Q4 (geschätzt; schmaler 128-Bit-Bus bremst Inferenz trotz 16GB)",
   "einschaetzung": "Schlechtes Preis-Leistungs-Verhältnis für LLMs: 16GB nützen wenig, wenn die Bandbreite (288 GB/s) unter einer 3060 liegt.",
   "link": "https://geizhals.de/asus-geforce-rtx-4060-ti-v131201.html"
  },
  {
   "name": "GeForce RTX 4070 Ti Super 16GB",
   "hersteller": "NVIDIA (Partner: ASUS, Gigabyte u.a.)",
   "kategorie": "gpu",
   "spezifikation": "16GB GDDR6X, 256-Bit-Bus, 672 GB/s",
   "vram_gb": 16,
   "ram_gb": null,
   "idle_watt": null,
   "tdp_watt": 285,
   "preis_eur": 1650,
   "benchmark": "~60-70 tok/s @7B-Q4 (geschätzt)",
   "einschaetzung": "Technisch stark (672 GB/s), aber 2026 nur noch überteuert als Restposten erhältlich – neu nicht empfehlenswert.",
   "link": "https://www.idealo.de/preisvergleich/ProductCategory/16073F104856976.html"
  },
  {
   "name": "GeForce RTX 4080 Super 16GB",
   "hersteller": "NVIDIA (Partner: MSI, Gigabyte u.a.)",
   "kategorie": "gpu",
   "spezifikation": "16GB GDDR6X, 256-Bit-Bus, 736 GB/s",
   "vram_gb": 16,
   "ram_gb": null,
   "idle_watt": null,
   "tdp_watt": 320,
   "preis_eur": 1775,
   "benchmark": "~65-75 tok/s @7B-Q4 (geschätzt)",
   "einschaetzung": "Sehr gute Inferenzleistung, aber zum aktuellen Preis fast doppelt so teuer wie MSRP – eine gebrauchte 3090 mit 24GB ist die klügere Wahl.",
   "link": "https://geizhals.de/msi-geforce-rtx-4080-super-v150949.html"
  },
  {
   "name": "GeForce RTX 3090 24GB (gebraucht)",
   "hersteller": "NVIDIA (gebraucht: diverse Hersteller)",
   "kategorie": "gpu",
   "spezifikation": "24GB GDDR6X, 384-Bit-Bus, 936 GB/s",
   "vram_gb": 24,
   "ram_gb": null,
   "idle_watt": null,
   "tdp_watt": 350,
   "preis_eur": 850,
   "benchmark": "~85-100 tok/s @7B-Q4 (geschätzt; 936 GB/s, Gebrauchtmarkt-KI-Champion)",
   "einschaetzung": "Bestes Preis-Leistungs-Verhältnis 2026: 24GB VRAM reichen für 32B-Q4 und 70B-Q3 – der Sweet Spot für lokale KI.",
   "link": "https://borncity.com/news/nvidia-rtx-3090-der-ungekroente-ki-koenig-des-gebrauchtmarkts/"
  },
  {
   "name": "GeForce RTX 4090 24GB",
   "hersteller": "NVIDIA (Partner: MSI, Gigabyte, ASUS u.a.)",
   "kategorie": "gpu",
   "spezifikation": "24GB GDDR6X, 384-Bit-Bus, 1008 GB/s",
   "vram_gb": 24,
   "ram_gb": null,
   "idle_watt": null,
   "tdp_watt": 450,
   "preis_eur": 3400,
   "benchmark": "~90-110 tok/s @7B-Q4 (gemessen, llama.cpp; markaicode)",
   "einschaetzung": "Schnellste Consumer-Karte für LLMs, aber Preis-Leistungs-Verhältnis schlecht – für 70B-Q4-Fans mit tiefem Budget.",
   "link": "https://geizhals.de/msi-geforce-rtx-4090-v112278.html"
  },
  {
   "name": "Radeon RX 7800 XT 16GB",
   "hersteller": "AMD (Partner: Sapphire u.a.)",
   "kategorie": "gpu",
   "spezifikation": "16GB GDDR6, 256-Bit-Bus, 624 GB/s",
   "vram_gb": 16,
   "ram_gb": null,
   "idle_watt": null,
   "tdp_watt": 263,
   "preis_eur": 1070,
   "benchmark": "~55-65 tok/s @7B-Q4 (geschätzt; Windows-ROCm/Vulkan mit spürbarem Overhead)",
   "einschaetzung": "Solide Bandbreite (624 GB/s), aber ROCm-Support unter Windows ist mühsam – für Ollama/llama.cpp-Nutzer nur bedingt zu empfehlen.",
   "link": "https://geizhals.de/sapphire-radeon-rx-7800-xt-v139043.html"
  },
  {
   "name": "GeForce RTX 5060 Ti 16GB",
   "hersteller": "NVIDIA (Partner: ASUS, MSI, Gigabyte u.a.)",
   "kategorie": "gpu",
   "spezifikation": "16GB GDDR7, 128-Bit-Bus, 448 GB/s",
   "vram_gb": 16,
   "ram_gb": null,
   "idle_watt": null,
   "tdp_watt": 180,
   "preis_eur": 685,
   "benchmark": "~40-50 tok/s @7B-Q4 (geschätzt; GDDR7, aber weiterhin 128-Bit)",
   "einschaetzung": "Aktueller Neukauf-Tipp für 16GB auf 7B-14B, aber GDDR7-Knappheit treibt den Preis – die gebrauchte 3090 bleibt die bessere Alternative.",
   "link": "https://geizhals.de/asus-dual-geforce-rtx-5060-ti-oc-90yv0mh0-m0na00-a3472689.html"
  },
  {
   "name": "Dell PowerEdge R730",
   "hersteller": "Dell",
   "kategorie": "server",
   "spezifikation": "2U Rack · Intel Xeon E5-2600 v3/v4 (LGA2011-3) · max 1,5 TB DDR4 ECC (24 DIMM) · 16x SFF 2,5\" (auch 8x LFF-Variante)",
   "vram_gb": null,
   "ram_gb": null,
   "idle_watt": 105,
   "tdp_watt": null,
   "preis_eur": 300,
   "benchmark": "",
   "einschaetzung": "Preis-Leistungs-Allrounder für Virtualisierung/NAS: solide Kerne + DDR4, aber 2U-Lüfter sind hörbar und 80–130 W Idle ziehen bei 24/7 spürbar.",
   "link": "https://serverdeals.at/de/model/dell-poweredge-r730"
  },
  {
   "name": "Dell PowerEdge R730xd",
   "hersteller": "Dell",
   "kategorie": "server",
   "spezifikation": "2U Rack (Storage) · Intel Xeon E5-2600 v3/v4 · max 1,5 TB DDR4 ECC · 12x LFF 3,5\" + 2x SFF rear (auch 24x/26x SFF)",
   "vram_gb": null,
   "ram_gb": null,
   "idle_watt": 140,
   "tdp_watt": null,
   "preis_eur": 350,
   "benchmark": "",
   "einschaetzung": "Für große NAS-/ZFS-Bestände mit 3,5\"-Platten ideal; mit vielen HDDs und Dual-CPU eher 120–160 W Idle und laut – eher Keller/Abstellraum.",
   "link": "https://serverdeals.at/de/model/dell-poweredge-r730xd"
  },
  {
   "name": "Dell PowerEdge R740",
   "hersteller": "Dell",
   "kategorie": "server",
   "spezifikation": "2U Rack · Intel Xeon Scalable 1./2. Gen (Skylake/Cascade Lake-SP) · max 3 TB DDR4 ECC · 16x SFF 2,5\" (auch 8x/12x LFF)",
   "vram_gb": null,
   "ram_gb": null,
   "idle_watt": 120,
   "tdp_watt": null,
   "preis_eur": 550,
   "benchmark": "",
   "einschaetzung": "Moderner und effizienter als R730 (jüngere CPU-Gen, niedrigere Idle-Werte bei Single-CPU), dafür teurer – lohnt für sparsamere 24/7-Labore mit Zukunftsspielraum.",
   "link": "https://serverdeals.at/de/model/dell-poweredge-r740"
  },
  {
   "name": "HP ProLiant DL360 Gen9",
   "hersteller": "HPE",
   "kategorie": "server",
   "spezifikation": "1U Rack · Intel Xeon E5-2600 v3/v4 · max 1,5 TB DDR4 ECC · 8x SFF 2,5\" (auch 4x LFF)",
   "vram_gb": null,
   "ram_gb": null,
   "idle_watt": 105,
   "tdp_watt": null,
   "preis_eur": 200,
   "benchmark": "",
   "einschaetzung": "Günstiger 1U-Einstieg mit wenig Stellfläche, aber kleine High-Speed-Lüfter = laut, und 1U schränkt Plattenausbau ein – nur fürs Rack mit Dämpfung.",
   "link": "https://serverdeals.at/de/model/hp-proliant-dl360-gen9"
  },
  {
   "name": "HP ProLiant DL380 Gen9",
   "hersteller": "HPE",
   "kategorie": "server",
   "spezifikation": "2U Rack · Intel Xeon E5-2600 v3/v4 · max 1,5 TB DDR4 ECC · 8x LFF 3,5\" oder 24x SFF 2,5\"",
   "vram_gb": null,
   "ram_gb": null,
   "idle_watt": 110,
   "tdp_watt": null,
   "preis_eur": 250,
   "benchmark": "",
   "einschaetzung": "Der HP-Klassiker fürs Homelab: flexibel (LFF oder SFF), Single-CPU mit SSDs schon ~70–110 W Idle erreichbar; Dual-CPU + Platten treiben Verbrauch und Lärm nach oben.",
   "link": "https://serverdeals.at/de/model/hp-proliant-dl380-gen9"
  },
  {
   "name": "HP ProLiant DL380 Gen10",
   "hersteller": "HPE",
   "kategorie": "server",
   "spezifikation": "2U Rack · Intel Xeon Scalable 1./2. Gen · max 3 TB DDR4 ECC · 8x LFF 3,5\" oder 24x SFF 2,5\"",
   "vram_gb": null,
   "ram_gb": null,
   "idle_watt": 150,
   "tdp_watt": null,
   "preis_eur": 600,
   "benchmark": "",
   "einschaetzung": "Neuere Gen10-Plattform mit DDR4-RDIMM und mehr Effizienz pro Kern, aber hohe Anschaffung und Idle oft über 120 W – erst sinnvoll, wenn mehr CPU-Leistung als beim Gen9 nötig.",
   "link": "https://serverdeals.at/de/model/hp-proliant-dl380-gen10"
  },
  {
   "name": "Dell PowerEdge T620",
   "hersteller": "Dell",
   "kategorie": "server",
   "spezifikation": "Tower (5U) · Intel Xeon E5-2600 v1/v2 (Sandy/Ivy Bridge-EP, DDR3) · max 768 GB DDR3 ECC · 8x LFF 3,5\" (auch 16x SFF)",
   "vram_gb": null,
   "ram_gb": null,
   "idle_watt": 120,
   "tdp_watt": null,
   "preis_eur": 300,
   "benchmark": "",
   "einschaetzung": "Der einzige Wohnzimmer-taugliche Kandidat: große, langsame Lüfter = angenehm leise, dafür ältere DDR3-Plattform mit relativ hohem Idle – gut fürs Büro/Abstellraum statt Rack-Schrank.",
   "link": "https://serverdeals.at/de/model/dell-poweredge-t620"
  },
  {
   "name": "Synology DiskStation DS223",
   "hersteller": "Synology",
   "kategorie": "nas",
   "spezifikation": "",
   "vram_gb": null,
   "ram_gb": null,
   "idle_watt": 8,
   "tdp_watt": null,
   "preis_eur": 278,
   "benchmark": "",
   "einschaetzung": "Günstiges 2-Bay-Value-NAS für reines Datei-/Foto-Backup ohne Container-Support (ARM, kein Docker) – für Self-Hosting mit Docker ungeeignet.",
   "link": "https://geizhals.de/synology-diskstation-ds223-a2893895.html"
  },
  {
   "name": "Synology DiskStation DS224+",
   "hersteller": "Synology",
   "kategorie": "nas",
   "spezifikation": "",
   "vram_gb": null,
   "ram_gb": null,
   "idle_watt": 11,
   "tdp_watt": null,
   "preis_eur": 369,
   "benchmark": "",
   "einschaetzung": "Kompaktes 2-Bay-Plus-NAS mit Docker (Container Manager) und geringem Stromverbrauch – idealer Einstieg fürs Homelab mit 1–2 Containern und Backup.",
   "link": "https://geizhals.de/synology-diskstation-ds224-a2990825.html"
  },
  {
   "name": "Synology DiskStation DS423+",
   "hersteller": "Synology",
   "kategorie": "nas",
   "spezifikation": "",
   "vram_gb": null,
   "ram_gb": null,
   "idle_watt": 11,
   "tdp_watt": null,
   "preis_eur": 540,
   "benchmark": "",
   "einschaetzung": "4-Bay-Plus-NAS mit Docker-Support und 2 NVMe-Cache-Slots, guter Allrounder fürs Homelab; Limit: nur 6 GB RAM und 1GbE ohne 10GbE-Option.",
   "link": "https://www.idealo.de/preisvergleich/OffersOfProduct/202432362_-diskstation-ds423-synology.html"
  },
  {
   "name": "Synology DiskStation DS923+",
   "hersteller": "Synology",
   "kategorie": "nas",
   "spezifikation": "",
   "vram_gb": null,
   "ram_gb": null,
   "idle_watt": 23,
   "tdp_watt": null,
   "preis_eur": 799,
   "benchmark": "",
   "einschaetzung": "Leistungsfähigstes Synology im Vergleich: ECC-RAM, 32 GB ausbaubar, 10GbE nachrüstbar und Docker – beste Wahl für ernsthaftes Homelab; kein iGPU (kein HW-Transcoding).",
   "link": "https://geizhals.de/synology-diskstation-ds923-a2846784.html"
  },
  {
   "name": "QNAP TS-464 (8G)",
   "hersteller": "QNAP",
   "kategorie": "nas",
   "spezifikation": "",
   "vram_gb": null,
   "ram_gb": null,
   "idle_watt": 20,
   "tdp_watt": null,
   "preis_eur": 699,
   "benchmark": "",
   "einschaetzung": "Vielseitiges 4-Bay-NAS mit 2.5GbE ab Werk, Intel-QuickSync-Transcoding und sehr gutem Docker-Support (Container Station) – starke, erweiterbare Homelab-Plattform.",
   "link": "https://geizhals.de/qnap-turbo-station-ts-464-8g-a2872932.html"
  },
  {
   "name": "QNAP TS-262 (4G)",
   "hersteller": "QNAP",
   "kategorie": "nas",
   "spezifikation": "",
   "vram_gb": null,
   "ram_gb": null,
   "idle_watt": 16,
   "tdp_watt": null,
   "preis_eur": 371,
   "benchmark": "",
   "einschaetzung": "Kompaktes 2-Bay-Multimedia-NAS mit 2.5GbE, QuickSync-Transcoding und Docker – gut für Media/Container im kleinen Homelab; Verfügbarkeit im DE-Handel derzeit eingeschränkt.",
   "link": "https://geizhals.de/qnap-turbo-station-ts-262-4g-a2825024.html"
  },
  {
   "name": "Ugreen NASync DXP4800 Plus",
   "hersteller": "Ugreen",
   "kategorie": "nas",
   "spezifikation": "",
   "vram_gb": null,
   "ram_gb": null,
   "idle_watt": 30,
   "tdp_watt": null,
   "preis_eur": 539,
   "benchmark": "",
   "einschaetzung": "Hardware-Preis-Leistungs-Sieger mit 10GbE, 64 GB RAM und starkem x86-Docker/VM-Support – aber höherer Idle-Verbrauch und jüngeres OS (UGOS Pro) als Synology/QNAP.",
   "link": "https://geizhals.de/ugreen-dxp4800-plus-a3162929.html"
  }
 ]
};
